### ISSUE TITLE
iPhone X compatible for TOP flushbar?

### ISSUE THREAD

**Issue by pkgundam** [AndreHaueisen/flushbar#12]
Hi - this is not an issue. Just checking about iPhone X compatible for TOP flushbar? thank you for the package. Really appreciate it.

**Comment by AndreHaueisen** [comment]
Hi @pkgundam 
I imagine you are worried about the notch.
In theory, it is compatible with iPhone X. Flushbar uses `SafeArea` widget.
I can not test it because I do not own a Mac. If you test it, please leave a comment here confirming or disproving my theory. It can help others with the same doubt.
Cheers :)

**Comment by pkgundam** [comment]
thank you for the response. It was working before I upgraded my flutter version. It was covering the notch properly. After I did flutter upgrade, the notch is not being covered. It is a very good library. thank you for that.

here is my info.

Flutter 0.8.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (2 weeks ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.3.1.flutter-760a9690c2

**Comment by AndreHaueisen** [comment]
Ok. Appreciate your help. I will take a look at the docs to see what changed in the new version.

I'm tagging this issue with **Help Wanted**  so other devs can help me test the support for IOS

**Comment by lifenautjoe** [comment]
Hi, thought I would just add that the same problem is for the bottom flushbar. 

I guess the solution would be not using the safearea and calculating the distance between the after the nodge and adding the rest as padding or... simply have the possibility of making the alerts rounded and smaller so they're bubbles instead of bars :-)

**Comment by AndreHaueisen** [comment]
Just tested on IOS. Notch is being handled properly.

**Comment by pdefuns** [comment]
Not closed for me. The notch are is blank (transparent). I would assume, that it should be filled with the background color

**Comment by AndreHaueisen** [comment]
Transparent background is the desired behavior. I was worried that the notch was covering the notification, but that is not the case.

**Comment by pdefuns** [comment]
If this is the right behaviour for you, is there a possibility to oversteer? To have both options 😃 

For me it looks very strange when the message is "flying over the notch" and has a transparent space. I'd prefer if the space would be filled as well (background color of the message). Then it would stick to the top of the phone but (the text) is not covered by the notch.

**Comment by AndreHaueisen** [comment]
As it turns out, it is simple to implement this. The feature is coming in the next version. Use FlushbarStyle.GROUNDED.
Thanks for the feedback.
