### ISSUE TITLE
Request to have indicator widget when in blocking mode

### ISSUE THREAD

**Issue by jasonlaw** [AndreHaueisen/flushbar#50]
Hi @AndreHaueisen ,

Would it be possible to have our custom indicator widget (such as hourglass) to display at the center of the page when in blocking mode?

Thanks in advance.

**Comment by AndreHaueisen** [comment]
@jasonlaw Hi. Sorry for the late response. Ended up forgetting to answer you.
I have a lot of work to do right now and can't spare a lot of time to implement new features. So, at least for now, the answer is no.
Will definitely consider this in the future though.
Thanks for the idea.

**Comment by davbaron** [comment]
@jasonlaw and @AndreHaueisen , I may have solved this issue.  I too wanted to see if I could use Flushbar as a 'HUD' type of dialog... So what I did was instead of using an 'icon', I use either a CircularProgressIndicator or CupertinoActivityIndicator (depending on platform). It *almost* works great, however there is one significant issue:  I want the 'progress dialog' to be modal, meaning, I do not want my users touching or interacting with my forms under the progress dialog while, for instance, I am saving their data to my API server. So, I include both an OverlayBlur value, and an OverlayColor value. Unfortunately, with both values set, Flutter's 'frames per second' drops almost to zero (if you give it enough time). It immediately 'slows down' and keeps slowing down, which means the 'indicator' literally crawls to a stop.  If I remove the Blur by setting it to zero, I get full 'speed', but I no longer get the overlay/color, meaning, it's not modal any longer and the user can fully interact with the widgets. I understand your code wants both values, since the BackdropFilter widget needs both.

One option here is to find out how the blur results in Flutter seizing up.

Could another option be having an overlay, but without the AnimatedBuilder/BackdropFilter?  Could a DecoratedBox (with alpha'd background color) do the trick?

BTW:  I tested this with a 'simple' setup, meaning, no special ProgressIndicator of my own at all.  Just a 'message', a standard Icon, and a 'flat button'... and the OverlayBlur and OverlayColor values. I get the same result, i.e., Flutter crawls to just a few frames per sec.

Let me know if you'd like sample code...but this should be pretty easy to reproduce...

Thank you...
