### ISSUE TITLE
AroundPadding rename

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [AndreHaueisen/flushbar#53]
isn't `aroundPadding` really a margin? Like Container's `margin` property adds space on the outside of the widget, and `padding` adds space inside the widget? I expect padding to make space between the left margin and the icon, for example.

**Comment by AndreHaueisen** [comment]
Hi @ThinkDigitalRepair 
Although you are right, in the code, `aroundPadding` adds padding to the child, hence the name; if it added space inside the widget I would simply call it `padding`.
Since `aroundPadding` is a synonym of `margin`, no value will be added if we make the swap so there is no reason to push a breaking change.

Thanks for the feedback though.
