### ISSUE TITLE
Why not use overlay for flushbar

### ISSUE THREAD

**Issue by ryanhz** [AndreHaueisen/flushbar#54]
It is fantastic to have flushbar, but it really mangles with the route state if you need to show flushbar at the same time you want to pop back to another page, which can also happen when user tap the back button on the phone.

**Comment by AndreHaueisen** [comment]
Hi @huzhiren 
Can you be more specific? What do you have in mind when you say overlay? Maybe I missed a possible solution here.

I don't know if you are already using it but Flushbar returns a Future that completes when it is fully dismissed. It can help you in the example you gave me.

**Comment by AndreHaueisen** [comment]
See [issue](https://github.com/AndreHaueisen/flushbar/issues/56)

**Comment by AndreHaueisen** [comment]
After testing it, I have discarded using Overlay widget. The overlay does not stay on the screen once the route gets popped so it brings no benefit once the back button is pressed.

**Comment by diegoveloper** [comment]
+1 to this issue , it would be great if Flushbar allow us using `Overlay` instead of the `Navigator`

**Comment by deakjahn** [comment]
Yes, a use case for you, because I'm thinking about how to solve this just now. :-)

The user does some operation that is confirmed with a Flushbar. While the Flushbar is still visible, the user swipes open the `Drawer` and selects an entry. The handler for that entry starts with a

    Navigator.pop(context);

as usual, to dismiss the open drawer before starting its own work. However, as the Fushbar is still visible on screen, this pop doesn't work, the drawer isn't dismissed.

A workaround would be, of course, to have a static function, something like `Flushbar.dismissAll()` to immediately dismiss any visible bars without actually keeping reference to them.

**Comment by deakjahn** [comment]
Just for reference, this is how I solved it. Create your own file with appropriate helper routines:

    Flushbar _flushBar;
    
    void successBar(BuildContext context, {String message, String title}) {
      _flushBar = Flushbar(
        title: title,
        message: message,
        ...
      );
      _flushBar.show(context);
    }
    
    void dismissBar() {
      if (_flushBar?.isShowing() ?? false) _flushBar.dismiss();
    }

and call `dismissBar()` whenever and wherever you have the chance of a flushbar being present (eg. before you pop a `Drawer` from the `Navigator`).
